#!/usr/bin/sh

echo "We will be running some post install scripts to tweak a few things"
read -p "Do you want to turn off function lock? (y/n) " fnlock
if [ ${fnlock,,} = "y" ]; then
    echo "options asus_wmi fnlock_default=N" | sudo tee -a /etc/modprobe.d/alsa-base.conf
    sudo update-initramfs -u -k all
    read -r -s -p $'Function lock has been disabled. Press enter to reboot...'
    reboot
fi

echo "Done!"