#!/usr/bin/sh
echo "NixOS Rebuilding..."
git add *
sudo nixos-rebuild switch --flake ~/dotfiles/
gen=$(nixos-rebuild list-generations --flake ~/dotfiles/ | grep -oP "[0-9]*(?= current)")
git commit -m "deployed $gen"
